// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMF-OIk8Fo4ifTCIdRa_76ekAyX65u9b0',
    appId: '1:621447900204:android:62133261db40bf41e97589',
    messagingSenderId: '621447900204',
    projectId: 'student-app-655d4',
    storageBucket: 'student-app-655d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxAq3y2GguWF4NfBPKrlIKbLG-T5574IA',
    appId: '1:621447900204:ios:673faa7002436274e97589',
    messagingSenderId: '621447900204',
    projectId: 'student-app-655d4',
    storageBucket: 'student-app-655d4.appspot.com',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtHkCa-gX8G2uwlpVQQwQ-FE_Zp-pBL60',
    appId: '1:621447900204:web:a3ff439d2ef73cffe97589',
    messagingSenderId: '621447900204',
    projectId: 'student-app-655d4',
    authDomain: 'student-app-655d4.firebaseapp.com',
    storageBucket: 'student-app-655d4.appspot.com',
  );
}
